name: eden-builder container

on:
    workflow_dispatch:
    push:
        branches:
            - dev
        paths:
            - "docker/eden-builder.Dockerfile"

jobs:
    eden-builder-container:
        name: eden-builder container
        runs-on: ubuntu-latest

        steps:
            - name: ✅ Checkout code
              uses: actions/checkout@v2

            - name: Preparation
              id: prep
              run: |
                  REGISTRY="ghcr.io"
                  IMAGE="${REGISTRY}/${{ github.repository_owner }}/eden-builder"
                  TAGS="${IMAGE}:${{ github.sha }}"
                  TAGS="${TAGS},${IMAGE}:latest"
                  echo ::set-output name=tags::${TAGS,,}

            - name: Showtag
              id: showtag
              run: echo ${{ steps.prep.outputs.tags }}

            - name: Docker Buildx setup
              uses: docker/setup-buildx-action@v1
              with:
                  buildkitd-flags: --debug

            - name: Login in to registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: 🛠 Build & Publish Image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  file: docker/eden-builder.Dockerfile
                  tags: ${{ steps.prep.outputs.tags }}
